name: Guestbook Entry
description: Sign my guestbook!
title: "Add Guestbook Entry"
labels: [guestbook]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for signing my guestbook! 🎉

  - type: textarea
    id: message
    attributes:
      label: Message
      description: Leave a nice message!
      placeholder: Hey there! Just wanted to say hi...
    validations:
      required: true