name: "✨ Guestbook Entry"
description: Sign my guestbook by leaving a message!
title: "✍️ New Guestbook Entry"
labels: ["guestbook"]
body:
  - type: textarea
    id: message
    attributes:
      label: "💌 Your Message"
      description: "What would you like to say? Feel free to use Markdown formatting!"
      placeholder: |
        Hi there! 👋
        
        Just wanted to say...
      render: markdown
    validations:
      required: true